'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.Sitemap = () => null; exports.getNavOptions = () => ({});
exports.Unmatched = () => null;
exports.canOverrideStatusBarBehavior = false;
exports.hideAsync = () => {}; exports._internal_maybeHideAsync = () => {}; exports.preventAutoHideAsync = () => {}; exports._internal_preventAutoHideAsync = () => {};
exports.useDomComponentNavigation = () => {};
exports.isNativeTabTrigger = () => false; exports.convertTabPropsToOptions = () => ({});
exports.Toast = () => null; exports.ToastWrapper = ({ children }) => children;
exports.Link = () => null; exports.Redirect = () => null;
exports.Tutorial = () => null;
