/**
 * Moodle calendar event names, per language.
 *
 * GENERATED by scripts/moodle-event-names.mjs from the Moodle 4.5 language
 * packs. Do not edit by hand — re-run the script.
 *
 * Moodle writes an event's name when the TEACHER saves the activity, in the
 * teacher's own language, so a school with Spanish-speaking staff and
 * English-speaking students produces Spanish event names. The placeholder is
 * not always at the start: English is '{$a} is due' but Spanish is
 * 'Vencimiento de {$a}', so each entry carries a prefix AND a suffix and the
 * parser strips both ends.
 *
 * Languages covered: en, es, pt_br, fr, de, it, ca, gl, eu, nl, pl, tr.
 * A school whose language is missing still works; the raw event name becomes
 * the task title and the parser reports it so the language can be added.
 */

/** What the parser does with an event carrying this name shape. */
export type MoodleEventKind = 'due' | 'open' | 'grading' | 'expect' | 'extend' | 'override';

export interface MoodleEventPattern {
  lang: string;
  /** The Moodle component the string belongs to, for tracing only. */
  comp: string;
  /** The language-pack key, for tracing only. */
  key: string;
  kind: MoodleEventKind;
  /** Text before the activity name. May be empty. */
  prefix: string;
  /** Text after the activity name. May be empty. */
  suffix: string;
}

/** Sorted longest-first, so 'is due to be graded' matches before 'is due'. */
export const MOODLE_EVENT_PATTERNS: readonly MoodleEventPattern[] = [
  {
    "lang": "pt_br",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " está com avaliação marcada para esta data"
  },
  {
    "lang": "tr",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " (değerlendirme için son teslim tarihi)"
  },
  {
    "lang": "pl",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " ostateczny termin przesyłania prac"
  },
  {
    "lang": "pl",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " (rozpoczyna się faza recenzowania)"
  },
  {
    "lang": "es",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " fecha límite para la evaluación"
  },
  {
    "lang": "eu",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": "(r)en entregatze-data (luzapena)"
  },
  {
    "lang": "pt_br",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " está marcado(a) para esta data"
  },
  {
    "lang": "fr",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " doit être rendu (prolongation)"
  },
  {
    "lang": "de",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " Abgabetermin für Beurteilungen"
  },
  {
    "lang": "pl",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " ostateczny termin recenzowania"
  },
  {
    "lang": "pt_br",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " - prazo limite para avaliação"
  },
  {
    "lang": "gl",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " (data límite das avaliacións)"
  },
  {
    "lang": "eu",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " ebaluazioetarako amaiera-data"
  },
  {
    "lang": "ca",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " data límit per a l'avaluació"
  },
  {
    "lang": "eu",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " bidalketetarako amaiera-data"
  },
  {
    "lang": "nl",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " moet klaar zijn (verlenging)"
  },
  {
    "lang": "pl",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " (przedłużony termin oddania)"
  },
  {
    "lang": "pl",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się przesyłanie prac"
  },
  {
    "lang": "pt_br",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " está vencido (prorrogação)"
  },
  {
    "lang": "it",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " è in scadenza (estensione)"
  },
  {
    "lang": "nl",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " gaat open voor beoordeling"
  },
  {
    "lang": "tr",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": "'nın süresi bittii (uzatma)"
  },
  {
    "lang": "tr",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "Gönderimler için ",
    "suffix": " son tarih"
  },
  {
    "lang": "fr",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " ouverture de l’évaluation"
  },
  {
    "lang": "de",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " ist zur Bewertung fällig."
  },
  {
    "lang": "de",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " ist fällig (Verlängerung)"
  },
  {
    "lang": "it",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " aperto per le valutazioni"
  },
  {
    "lang": "gl",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " pendente de cualificación"
  },
  {
    "lang": "gl",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " (aberto para avaliacións)"
  },
  {
    "lang": "eu",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " hasiko da bidalketa-fasea"
  },
  {
    "lang": "eu",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " hasiko da ebaluazio-fasea"
  },
  {
    "lang": "nl",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " deadline voor beoordeling"
  },
  {
    "lang": "pl",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " - termin wystawienia ocen"
  },
  {
    "lang": "tr",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " değerlendirme için açıldı"
  },
  {
    "lang": "en",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " deadline for submissions"
  },
  {
    "lang": "es",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " fecha límite para envíos"
  },
  {
    "lang": "pt_br",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " - prazo limite de envios"
  },
  {
    "lang": "de",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " Beginn der Beurteilungen"
  },
  {
    "lang": "ca",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " hauria d'estar completat"
  },
  {
    "lang": "gl",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " debería estar completada"
  },
  {
    "lang": "nl",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " moet nog voltooid worden"
  },
  {
    "lang": "pl",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " powinno zostać ukończone"
  },
  {
    "lang": "en",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " deadline for assessment"
  },
  {
    "lang": "es",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " se abre para evaluación"
  },
  {
    "lang": "pt_br",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " - início para avaliação"
  },
  {
    "lang": "fr",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " délai pour l’évaluation"
  },
  {
    "lang": "ca",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " (inici de les trameses)"
  },
  {
    "lang": "ca",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " data límit per trametre"
  },
  {
    "lang": "gl",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "Péchanse os comentarios ",
    "suffix": ""
  },
  {
    "lang": "nl",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " gaat open voor insturen"
  },
  {
    "lang": "es",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " ha vencido (extensión)"
  },
  {
    "lang": "es",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " debería ser completado"
  },
  {
    "lang": "de",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "Abschluss erwartet für ",
    "suffix": ""
  },
  {
    "lang": "ca",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " obre per a l'avaluació"
  },
  {
    "lang": "gl",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "Ábrense os comentarios ",
    "suffix": ""
  },
  {
    "lang": "nl",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " moet worden ingeleverd"
  },
  {
    "lang": "nl",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " moet worden beoordeeld"
  },
  {
    "lang": "nl",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " deadline voor insturen"
  },
  {
    "lang": "tr",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " başvurular için açıldı"
  },
  {
    "lang": "en",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " opens for submissions"
  },
  {
    "lang": "fr",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " ouverture des remises"
  },
  {
    "lang": "ca",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "La consulta s'obre el ",
    "suffix": ""
  },
  {
    "lang": "eu",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": "(r)en kalifikazio-data"
  },
  {
    "lang": "en",
    "comp": "workshop",
    "key": "assessmentstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " opens for assessment"
  },
  {
    "lang": "pt_br",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " deve estar concluído"
  },
  {
    "lang": "it",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " deve essere valutato"
  },
  {
    "lang": "it",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Personalzizzazione"
  },
  {
    "lang": "ca",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "La consulta ",
    "suffix": " es tanca"
  },
  {
    "lang": "eu",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en entregatze-data"
  },
  {
    "lang": "en",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " is due to be graded"
  },
  {
    "lang": "en",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " should be completed"
  },
  {
    "lang": "es",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " se abre para envíos"
  },
  {
    "lang": "it",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Personalizzazione"
  },
  {
    "lang": "it",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "Devi intervenire in ",
    "suffix": ""
  },
  {
    "lang": "it",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " fine delle consegne"
  },
  {
    "lang": "gl",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " pendente de entrega"
  },
  {
    "lang": "gl",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " pendente de entrega"
  },
  {
    "lang": "gl",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " comezo das entregas"
  },
  {
    "lang": "en",
    "comp": "assign",
    "key": "calendarextension",
    "kind": "extend",
    "prefix": "",
    "suffix": " is due (extension)"
  },
  {
    "lang": "pt_br",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " - início de envios"
  },
  {
    "lang": "ca",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " s'ha de qualificar"
  },
  {
    "lang": "eu",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": "(r)en hasiera-data:"
  },
  {
    "lang": "eu",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en itxiera-data:"
  },
  {
    "lang": "eu",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en itxiera-data:"
  },
  {
    "lang": "eu",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en itxiera-data:"
  },
  {
    "lang": "eu",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en itxiera-data:"
  },
  {
    "lang": "eu",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en itxiera-data:"
  },
  {
    "lang": "eu",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en itxiera-data:"
  },
  {
    "lang": "es",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " se debe calificar"
  },
  {
    "lang": "fr",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " doit être achevée"
  },
  {
    "lang": "eu",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": "(r)en amaiera-data"
  },
  {
    "lang": "eu",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": "(r)en hasiera-data"
  },
  {
    "lang": "eu",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": "(r)en hasiera-data"
  },
  {
    "lang": "eu",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": "(r)en hasiera-data"
  },
  {
    "lang": "eu",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": "(r)en hasiera-data"
  },
  {
    "lang": "eu",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": "(r)en hasiera-data"
  },
  {
    "lang": "fr",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " doit être évalué"
  },
  {
    "lang": "de",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Überschreibung"
  },
  {
    "lang": "it",
    "comp": "workshop",
    "key": "assessmentendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " fine valutazioni"
  },
  {
    "lang": "gl",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " fin das entregas"
  },
  {
    "lang": "nl",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Overschrijving"
  },
  {
    "lang": "pl",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " (termin oddania)"
  },
  {
    "lang": "pl",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "Termin wykonania ",
    "suffix": ""
  },
  {
    "lang": "fr",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " doit être rendu"
  },
  {
    "lang": "fr",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " délai de remise"
  },
  {
    "lang": "it",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " Inizio consegne"
  },
  {
    "lang": "nl",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " moet klaar zijn"
  },
  {
    "lang": "es",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "Vencimiento de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Sobreposição"
  },
  {
    "lang": "pt_br",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Sobreposição"
  },
  {
    "lang": "gl",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Sobrescribir"
  },
  {
    "lang": "eu",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " osatu behar da"
  },
  {
    "lang": "pl",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}\n"
  },
  {
    "lang": "tr",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " süresi doluyor"
  },
  {
    "lang": "tr",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Geçersiz kıl"
  },
  {
    "lang": "tr",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - geçersiz kıl"
  },
  {
    "lang": "tr",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " süresi doluyor"
  },
  {
    "lang": "en",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "en",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "es",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "es",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "pt_br",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "pt_br",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "fr",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "fr",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "de",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "de",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "it",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " è in scadenza"
  },
  {
    "lang": "it",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "it",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "it",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " da completare"
  },
  {
    "lang": "ca",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "ca",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "ca",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "Venciment del ",
    "suffix": ""
  },
  {
    "lang": "gl",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "gl",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "eu",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Salbuespena"
  },
  {
    "lang": "eu",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "eu",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Salbuespena"
  },
  {
    "lang": "eu",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "nl",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "nl",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Overschrijf"
  },
  {
    "lang": "nl",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "pl",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "tr",
    "comp": "assign",
    "key": "calendargradingdue",
    "kind": "grading",
    "prefix": "",
    "suffix": " not verilecek"
  },
  {
    "lang": "tr",
    "comp": "assign",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "tr",
    "comp": "quiz",
    "key": "overridegroupeventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - {$a->group}"
  },
  {
    "lang": "fr",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Dérogation"
  },
  {
    "lang": "fr",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Dérogation"
  },
  {
    "lang": "de",
    "comp": "workshop",
    "key": "submissionstartevent",
    "kind": "open",
    "prefix": "",
    "suffix": " Abgabebeginn"
  },
  {
    "lang": "de",
    "comp": "workshop",
    "key": "submissionendevent",
    "kind": "due",
    "prefix": "",
    "suffix": " Abgabetermin"
  },
  {
    "lang": "ca",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "Venciment de ",
    "suffix": ""
  },
  {
    "lang": "pl",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - nadpisanie"
  },
  {
    "lang": "pl",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - nadpisanie"
  },
  {
    "lang": "tr",
    "comp": "completion",
    "key": "completionexpectedfor",
    "kind": "expect",
    "prefix": "",
    "suffix": " tamamlanmalı"
  },
  {
    "lang": "es",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Excepción"
  },
  {
    "lang": "es",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Excepción"
  },
  {
    "lang": "de",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " ist fällig."
  },
  {
    "lang": "de",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " ist fällig."
  },
  {
    "lang": "ca",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " es tanca el"
  },
  {
    "lang": "ca",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " es tanca el"
  },
  {
    "lang": "nl",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " zal sluiten"
  },
  {
    "lang": "pl",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się"
  },
  {
    "lang": "pl",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się"
  },
  {
    "lang": "pl",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się"
  },
  {
    "lang": "pl",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się"
  },
  {
    "lang": "pl",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się"
  },
  {
    "lang": "pl",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " otwiera się"
  },
  {
    "lang": "en",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Override"
  },
  {
    "lang": "en",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Override"
  },
  {
    "lang": "pt_br",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "Término de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "Término de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "Término de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "Término de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "Término de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "Término de ",
    "suffix": ""
  },
  {
    "lang": "fr",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " se termine"
  },
  {
    "lang": "fr",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " se termine"
  },
  {
    "lang": "fr",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " se termine"
  },
  {
    "lang": "fr",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " se termine"
  },
  {
    "lang": "fr",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " se termine"
  },
  {
    "lang": "fr",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " se termine"
  },
  {
    "lang": "de",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Änderung"
  },
  {
    "lang": "ca",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Excepció"
  },
  {
    "lang": "ca",
    "comp": "quiz",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Excepció"
  },
  {
    "lang": "nl",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " zal openen"
  },
  {
    "lang": "pl",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " zamyka się"
  },
  {
    "lang": "pl",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " zamyka się"
  },
  {
    "lang": "pl",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " zamyka się"
  },
  {
    "lang": "pl",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " zamyka się"
  },
  {
    "lang": "pl",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " zamyka się"
  },
  {
    "lang": "pl",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " zamyka się"
  },
  {
    "lang": "tr",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " başlayacak"
  },
  {
    "lang": "es",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "Se cierra ",
    "suffix": ""
  },
  {
    "lang": "es",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " pendiente"
  },
  {
    "lang": "pt_br",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "Início de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "Início de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "Início de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "Início de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "Início de ",
    "suffix": ""
  },
  {
    "lang": "pt_br",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "Início de ",
    "suffix": ""
  },
  {
    "lang": "ca",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " s'obre el"
  },
  {
    "lang": "ca",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " s'obre el"
  },
  {
    "lang": "tr",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " kapanacak"
  },
  {
    "lang": "tr",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " kapanacak"
  },
  {
    "lang": "tr",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " kapanıyor"
  },
  {
    "lang": "tr",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " kapanıyor"
  },
  {
    "lang": "tr",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " kapanıyor"
  },
  {
    "lang": "tr",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " kapanacak"
  },
  {
    "lang": "pt_br",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " é devido"
  },
  {
    "lang": "fr",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "Délai de ",
    "suffix": ""
  },
  {
    "lang": "de",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "'",
    "suffix": "' endet."
  },
  {
    "lang": "ca",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " es tanca"
  },
  {
    "lang": "ca",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " es tanca"
  },
  {
    "lang": "gl",
    "comp": "assign",
    "key": "overrideusereventname",
    "kind": "override",
    "prefix": "",
    "suffix": " - Anular"
  },
  {
    "lang": "tr",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " açılacak"
  },
  {
    "lang": "tr",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " açılıyor"
  },
  {
    "lang": "tr",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " açılıyor"
  },
  {
    "lang": "tr",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " açılıyor"
  },
  {
    "lang": "tr",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " açılacak"
  },
  {
    "lang": "es",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "Se abre ",
    "suffix": ""
  },
  {
    "lang": "es",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " cierran"
  },
  {
    "lang": "fr",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " s’ouvre"
  },
  {
    "lang": "fr",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " s’ouvre"
  },
  {
    "lang": "fr",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " s’ouvre"
  },
  {
    "lang": "fr",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " s’ouvre"
  },
  {
    "lang": "fr",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " s’ouvre"
  },
  {
    "lang": "fr",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " s’ouvre"
  },
  {
    "lang": "de",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " beginnt"
  },
  {
    "lang": "de",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " beginnt"
  },
  {
    "lang": "de",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " beginnt"
  },
  {
    "lang": "de",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " beginnt"
  },
  {
    "lang": "de",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " beginnt"
  },
  {
    "lang": "de",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " beginnt"
  },
  {
    "lang": "en",
    "comp": "assign",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " is due"
  },
  {
    "lang": "en",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " closes"
  },
  {
    "lang": "en",
    "comp": "forum",
    "key": "calendardue",
    "kind": "due",
    "prefix": "",
    "suffix": " is due"
  },
  {
    "lang": "en",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " closes"
  },
  {
    "lang": "en",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " closes"
  },
  {
    "lang": "en",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " closes"
  },
  {
    "lang": "en",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " closes"
  },
  {
    "lang": "en",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " closes"
  },
  {
    "lang": "es",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " cierra"
  },
  {
    "lang": "es",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " cierra"
  },
  {
    "lang": "es",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " cierra"
  },
  {
    "lang": "es",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " cierre"
  },
  {
    "lang": "it",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " chiude"
  },
  {
    "lang": "it",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " chiude"
  },
  {
    "lang": "it",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " chiude"
  },
  {
    "lang": "it",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " chiude"
  },
  {
    "lang": "it",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " chiude"
  },
  {
    "lang": "it",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " chiude"
  },
  {
    "lang": "ca",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " s'obre"
  },
  {
    "lang": "ca",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " s'obre"
  },
  {
    "lang": "gl",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " aberta"
  },
  {
    "lang": "gl",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " pechan"
  },
  {
    "lang": "gl",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " pechan"
  },
  {
    "lang": "gl",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " pechan"
  },
  {
    "lang": "gl",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " pechan"
  },
  {
    "lang": "gl",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " pechan"
  },
  {
    "lang": "en",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " opens"
  },
  {
    "lang": "en",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " opens"
  },
  {
    "lang": "en",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opens"
  },
  {
    "lang": "en",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opens"
  },
  {
    "lang": "en",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opens"
  },
  {
    "lang": "en",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opens"
  },
  {
    "lang": "es",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abren"
  },
  {
    "lang": "de",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " endet"
  },
  {
    "lang": "de",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " endet"
  },
  {
    "lang": "de",
    "comp": "choice",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " endet"
  },
  {
    "lang": "de",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " endet"
  },
  {
    "lang": "de",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " endet"
  },
  {
    "lang": "gl",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " abren"
  },
  {
    "lang": "gl",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abren"
  },
  {
    "lang": "gl",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abren"
  },
  {
    "lang": "gl",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abren"
  },
  {
    "lang": "nl",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " opent"
  },
  {
    "lang": "nl",
    "comp": "quiz",
    "key": "quizeventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " sluit"
  },
  {
    "lang": "nl",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " opent"
  },
  {
    "lang": "nl",
    "comp": "lesson",
    "key": "lessoneventcloses",
    "kind": "due",
    "prefix": "",
    "suffix": " sluit"
  },
  {
    "lang": "nl",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opent"
  },
  {
    "lang": "nl",
    "comp": "feedback",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " sluit"
  },
  {
    "lang": "nl",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opent"
  },
  {
    "lang": "nl",
    "comp": "data",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " sluit"
  },
  {
    "lang": "nl",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " opent"
  },
  {
    "lang": "nl",
    "comp": "scorm",
    "key": "calendarend",
    "kind": "due",
    "prefix": "",
    "suffix": " sluit"
  },
  {
    "lang": "es",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " abre"
  },
  {
    "lang": "es",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abre"
  },
  {
    "lang": "es",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abre"
  },
  {
    "lang": "es",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " abre"
  },
  {
    "lang": "it",
    "comp": "quiz",
    "key": "quizeventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " apre"
  },
  {
    "lang": "it",
    "comp": "lesson",
    "key": "lessoneventopens",
    "kind": "open",
    "prefix": "",
    "suffix": " apre"
  },
  {
    "lang": "it",
    "comp": "choice",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " apre"
  },
  {
    "lang": "it",
    "comp": "feedback",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " apre"
  },
  {
    "lang": "it",
    "comp": "data",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " apre"
  },
  {
    "lang": "it",
    "comp": "scorm",
    "key": "calendarstart",
    "kind": "open",
    "prefix": "",
    "suffix": " apre"
  }
];

/**
 * Moodle's own UI labels, per language.
 *
 * `siteevents` is the shortname of the synthetic pseudo-course the export adds
 * under preset_what=all; the parser uses it to tell a real course from that.
 * The rest are the button names the setup card quotes, so the card says what
 * the student's Moodle actually says.
 */
export const MOODLE_LABELS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "en": {
    "siteevents": "Site events",
    "generateurlbutton": "Get calendar URL",
    "exportcalendar": "Export calendar",
    "managesubscriptions": "Import or export calendars",
    "exportbutton": "Export"
  },
  "es": {
    "siteevents": "Eventos Globales",
    "generateurlbutton": "Obtener URL del calendario",
    "exportcalendar": "Exportar calendario",
    "managesubscriptions": "Importar o exportar calendarios",
    "exportbutton": "Exportar"
  },
  "pt_br": {
    "siteevents": "Eventos de site",
    "generateurlbutton": "Obter URL do calendário",
    "exportcalendar": "Exportar calendário",
    "managesubscriptions": "Gerenciar assinaturas",
    "exportbutton": "Exportar"
  },
  "fr": {
    "siteevents": "Événements de site",
    "generateurlbutton": "URL du calendrier",
    "exportcalendar": "Exporter le calendrier",
    "managesubscriptions": "Importer ou exporter des calendriers",
    "exportbutton": "Exporter"
  },
  "de": {
    "siteevents": "Website-Termine",
    "generateurlbutton": "Kalender-URL abfragen",
    "exportcalendar": "Kalender exportieren",
    "managesubscriptions": "Import und Export",
    "exportbutton": "Export"
  },
  "it": {
    "siteevents": "Eventi del sito",
    "generateurlbutton": "URL del calendario",
    "exportcalendar": "Esporta calendario",
    "managesubscriptions": "Importa o esporta calendari",
    "exportbutton": "Esportazione"
  },
  "ca": {
    "siteevents": "Esdeveniments del lloc",
    "generateurlbutton": "Genera l'URL del calendari",
    "exportcalendar": "Exporta el calendari",
    "managesubscriptions": "Importa o exporta calendaris",
    "exportbutton": "Exporta"
  },
  "gl": {
    "siteevents": "Eventos do sitio",
    "generateurlbutton": "Obter o URL do calendario",
    "exportcalendar": "Exportar calendario",
    "managesubscriptions": "Importar ou exportar calendarios",
    "exportbutton": "Exportar"
  },
  "eu": {
    "siteevents": "Guneko ekitaldiak",
    "generateurlbutton": "Eskuratu egutegiaren URLa",
    "exportcalendar": "Esportatu egutegia",
    "managesubscriptions": "Inportatu edo esportatu egutegiak",
    "exportbutton": "Esportatu"
  },
  "nl": {
    "siteevents": "Site-gebeurtenissen",
    "generateurlbutton": "Haal URL kalender",
    "exportcalendar": "Exporteer kalender",
    "managesubscriptions": "Importeer of exporteer kalenders",
    "exportbutton": "Exporteer"
  },
  "pl": {
    "siteevents": "Wydarzenia strony",
    "generateurlbutton": "Pobierz adres URL kalendarza",
    "exportcalendar": "Eksportuj kalendarz",
    "managesubscriptions": "Importuj lub eksportuj kalendarze",
    "exportbutton": "Eksport"
  },
  "tr": {
    "siteevents": "Site olayları",
    "generateurlbutton": "Takvim URL'si getir",
    "exportcalendar": "Takvimi dışa ver",
    "managesubscriptions": "Takvimleri içe veya dışa aktarma",
    "exportbutton": "Dışa aktar"
  }
};

/** Every localisation of the site-events pseudo-course shortname. */
export const MOODLE_SITE_EVENT_NAMES: readonly string[] = [
  "Esdeveniments del lloc",
  "Eventi del sito",
  "Eventos Globales",
  "Eventos de site",
  "Eventos do sitio",
  "Guneko ekitaldiak",
  "Site events",
  "Site olayları",
  "Site-gebeurtenissen",
  "Website-Termine",
  "Wydarzenia strony",
  "Événements de site"
];
