const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Teach release builds to use the real upload keystore.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, and the template
 * it regenerates ships a release buildType signed with **debug.keystore** — the
 * generated comment even says "Caution! In production, you need to generate your
 * own keystore file." Hand-editing android/app/build.gradle therefore survives
 * exactly until the next prebuild, which is why this is a config plugin instead.
 *
 * No secrets live here or anywhere in the repo. The four values are read from
 * Gradle properties, which are set in ~/.gradle/gradle.properties on the machine
 * doing the build. If they are absent the release config is simply not applied,
 * so a checkout without the keystore still builds (debug-signed) rather than
 * failing — which is what CI and a fresh clone want.
 */
const PROPS = {
  storeFile: 'SEMORA_UPLOAD_STORE_FILE',
  storePassword: 'SEMORA_UPLOAD_STORE_PASSWORD',
  keyAlias: 'SEMORA_UPLOAD_KEY_ALIAS',
  keyPassword: 'SEMORA_UPLOAD_KEY_PASSWORD',
};

const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('${PROPS.storeFile}')) {
                storeFile file(${PROPS.storeFile})
                storePassword ${PROPS.storePassword}
                keyAlias ${PROPS.keyAlias}
                keyPassword ${PROPS.keyPassword}
            }
        }
`;

module.exports = function withAndroidUploadSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let src = cfg.modResults.contents;

    if (src.includes(PROPS.storeFile)) return cfg; // already applied

    // 1. Add a `release` entry alongside the template's `debug` signingConfig.
    const debugBlockEnd = src.indexOf("keyPassword 'android'");
    if (debugBlockEnd === -1) {
      throw new Error('withAndroidUploadSigning: could not find the debug signingConfig to anchor to.');
    }
    const closeOfDebug = src.indexOf('}', debugBlockEnd);
    const insertAt = src.indexOf('\n', closeOfDebug) + 1;
    src = src.slice(0, insertAt) + RELEASE_SIGNING_CONFIG + src.slice(insertAt);

    // 2. Point the release buildType at it — only when the properties exist, so
    //    a machine without the keystore still produces a (debug-signed) build.
    const before = `            signingConfig signingConfigs.debug
            def enableShrinkResources`;
    const after = `            signingConfig project.hasProperty('${PROPS.storeFile}') ? signingConfigs.release : signingConfigs.debug
            def enableShrinkResources`;
    if (!src.includes(before)) {
      throw new Error('withAndroidUploadSigning: could not find the release buildType signingConfig line.');
    }
    src = src.replace(before, after);

    cfg.modResults.contents = src;
    return cfg;
  });
};
