import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator, Alert, Platform, ScrollView, StyleSheet, Switch,
  Text, TouchableOpacity, View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useFocusEffect, useRouter } from 'expo-router';
import FontAwesome from '@expo/vector-icons/FontAwesome';
import * as Haptics from 'expo-haptics';
import { format, isToday, isTomorrow } from 'date-fns';
import { useAppStore } from '@/store/appStore';
import {
  useCourses, useReplaceStudyPlan, useStudyBlocks, useStudyPlannerSettings,
  useTasks, useToggleStudyBlock, useUpdateStudyPlannerSettings,
  type StudyBlockWithTask,
} from '@/lib/queries';
import {
  DAILY_MINUTE_OPTIONS, DEFAULT_STUDY_PLANNER_SETTINGS, STUDY_SESSION_OPTIONS,
  STUDY_PLAN_HORIZON_DAYS, FREE_STUDY_PLAN_HORIZON_DAYS, formatStudyDuration, generateStudyPlan, type GeneratedStudyPlan,
} from '@/lib/studyPlanner';
import { getPlannerCalendarConflicts } from '@/lib/plannerCalendar';
import type { StudyPlannerSettings, StudySessionMinutes } from '@/types/database';
import { DatePicker } from '@/components/DatePicker';
import { useColors } from '@/lib/theme';
import { useResponsive } from '@/lib/responsive';
import { COLORS, FONTS, SCREEN_MAX_WIDTH } from '@/lib/constants';
import { formatLocalDate } from '@/lib/dates';
import { formatTimeOfDay } from '@/lib/schedule';
import { track } from '@/lib/analytics';

function timeToDate(value: string) {
  const [hours, minutes] = value.split(':').map(Number);
  const date = new Date();
  date.setHours(hours || 0, minutes || 0, 0, 0);
  return date;
}

function dateToTime(value: Date) {
  return `${String(value.getHours()).padStart(2, '0')}:${String(value.getMinutes()).padStart(2, '0')}:00`;
}

function dayLabel(dateKey: string) {
  const date = new Date(`${dateKey}T00:00:00`);
  if (isToday(date)) return 'Today';
  if (isTomorrow(date)) return 'Tomorrow';
  return format(date, 'EEEE, MMM d');
}

export default function PlannerScreen() {
  const router = useRouter();
  const colors = useColors();
  const { contentMaxWidth } = useResponsive();
  const isPro = useAppStore((state) => state.isPro);
  // Free users get a working plan over a shorter window rather than a locked
  // screen — see FREE_STUDY_PLAN_HORIZON_DAYS. The server enforces the same
  // cap (migration 049), so this is presentation, not the security boundary.
  const horizonDays = isPro ? STUDY_PLAN_HORIZON_DAYS : FREE_STUDY_PLAN_HORIZON_DAYS;
  const semesterId = useAppStore((state) => state.selectedSemesterId);
  const { data: tasks = [], isLoading: tasksLoading } = useTasks(
    semesterId ? { semesterId } : { semesterId: null },
  );
  const { data: courses = [], isLoading: coursesLoading } = useCourses(semesterId);
  const { data: blocks = [], isLoading: blocksLoading } = useStudyBlocks(semesterId);
  const { data: remoteSettings, isLoading: settingsLoading } = useStudyPlannerSettings();
  const replacePlan = useReplaceStudyPlan();
  const updateSettings = useUpdateStudyPlannerSettings();
  const toggleBlock = useToggleStudyBlock();
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [draftSettings, setDraftSettings] = useState<StudyPlannerSettings>(DEFAULT_STUDY_PLANNER_SETTINGS);
  const [lastPlan, setLastPlan] = useState<GeneratedStudyPlan | null>(null);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [plannerNote, setPlannerNote] = useState<string | null>(null);
  const autoGeneratedFor = useRef<string | null>(null);

  useEffect(() => {
    if (remoteSettings) setDraftSettings(remoteSettings);
  }, [remoteSettings]);

  useEffect(() => {
    track('smart_planner_viewed', { screen: 'planner' });
  }, []);

  const meetings = useMemo(
    () => courses.flatMap((course) => course.course_meetings || []),
    [courses],
  );

  const buildAndSave = useCallback(async (
    settings: StudyPlannerSettings,
    reason: 'automatic' | 'manual' | 'settings',
  ) => {
    if (!semesterId) return;
    setGenerationError(null);
    const now = new Date();
    const missedCount = blocks.filter((block) =>
      !block.is_completed &&
      (block.scheduled_date < formatLocalDate(now) ||
        (block.scheduled_date === formatLocalDate(now) && block.start_time < format(now, 'HH:mm:ss'))),
    ).length;
    const missedByTask = new Map<string, string>();
    for (const block of blocks) {
      const missed = !block.is_completed &&
        (block.scheduled_date < formatLocalDate(now) ||
          (block.scheduled_date === formatLocalDate(now) && block.start_time < format(now, 'HH:mm:ss')));
      if (missed && !missedByTask.has(block.task_id)) missedByTask.set(block.task_id, block.scheduled_date);
    }
    const calendar = settings.study_avoid_calendar_conflicts
      ? await getPlannerCalendarConflicts(now, horizonDays, reason === 'settings')
      : { intervals: [], permission: 'denied' as const };
    const generated = generateStudyPlan(
      tasks, meetings, blocks, settings, now, horizonDays, calendar.intervals,
    );
    try {
      await replacePlan.mutateAsync({
        semesterId,
        blocks: generated.blocks.map((block) => ({
          task_id: block.task_id,
          scheduled_date: block.scheduled_date,
          start_time: block.start_time,
          duration_minutes: block.duration_minutes,
          reschedule_reason: missedByTask.has(block.task_id) ? 'missed' : reason === 'manual' ? 'rebuild' : null,
          rescheduled_from_date: missedByTask.get(block.task_id) || null,
        })),
      });
      setLastPlan(generated);
      const notes: string[] = [];
      if (missedCount > 0) notes.push(`${missedCount} missed session${missedCount === 1 ? '' : 's'} moved forward`);
      if (settings.study_avoid_calendar_conflicts) {
        notes.push(calendar.permission === 'granted'
          ? `${calendar.intervals.length} calendar conflict${calendar.intervals.length === 1 ? '' : 's'} avoided`
          : 'Class conflicts avoided · calendar access unavailable');
      }
      setPlannerNote(notes.join(' · ') || 'Plan rebuilt from your latest deadlines');
      track('smart_plan_generated', {
        reason,
        sessions: generated.blocks.length,
        minutes: generated.totalPlannedMinutes,
        unscheduled_minutes: generated.unscheduledMinutes,
        at_risk_minutes: generated.atRiskMinutes,
      });
      if (Platform.OS === 'ios' && reason !== 'automatic') {
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
      }
    } catch (error: any) {
      setGenerationError(error?.message || 'Could not build your plan.');
      if (reason !== 'automatic') Alert.alert('Couldn’t rebuild plan', error?.message || 'Please try again.');
    }
  }, [semesterId, tasks, meetings, blocks, replacePlan]);

  // Opening Smart Plan is the reschedule action: completed sessions remain in
  // history, while every unfinished block is deterministically rebuilt from
  // today forward using the latest tasks, settings, and class schedule. This
  // runs on every screen FOCUS (not just mount) so returning to the tab always
  // carries missed sessions forward — a user who leaves the app open for days
  // still gets a fresh plan the next time they land here. The rebuild is
  // idempotent: generateStudyPlan is deterministic and the replace RPC removes
  // and rebuilds open blocks while preserving completed ones, so re-running
  // never duplicates work.
  const runAutoReschedule = useCallback(() => {
    if (!isPro || !semesterId || !remoteSettings || !remoteSettings.study_auto_reschedule) return;
    if (tasksLoading || coursesLoading || blocksLoading || settingsLoading) return;
    // Skip a redundant rebuild if we already generated for this semester on this
    // focus pass and nothing above changed; the ref is cleared on blur so the
    // next visit always recomputes.
    if (autoGeneratedFor.current === semesterId) return;
    autoGeneratedFor.current = semesterId;
    buildAndSave(remoteSettings, 'automatic');
  }, [
    isPro, semesterId, remoteSettings, tasksLoading, coursesLoading,
    blocksLoading, settingsLoading, buildAndSave,
  ]);

  // Held in a ref so the focus effect below can take an EMPTY dep array.
  //
  // useMutation returns a new object on every render (react-query's useMutation
  // literally does `return { ...result, mutate, mutateAsync }`), so `replacePlan`
  // changes identity each render -> so does `buildAndSave`, and so does
  // `runAutoReschedule`. A focus effect depending on it therefore re-subscribed
  // on EVERY render: React ran the cleanup — which clears `autoGeneratedFor`,
  // deliberately defeating the guard — and then re-ran the effect, firing
  // another full replace_study_plan RPC and another device-calendar read. With
  // study_auto_reschedule and study_avoid_calendar_conflicts both defaulting to
  // true, opening this tab as a Pro user was a continuous write loop.
  const runAutoRescheduleRef = useRef(runAutoReschedule);
  runAutoRescheduleRef.current = runAutoReschedule;

  useFocusEffect(
    useCallback(() => {
      runAutoRescheduleRef.current();
      // Now that this only fires on real focus/blur, clearing the guard here is
      // safe again: the next visit recomputes with the day's data as it stands,
      // carrying newly-missed work forward.
      return () => { autoGeneratedFor.current = null; };
    }, []),
  );

  const todayKey = formatLocalDate(new Date());
  const visibleBlocks = blocks.filter((block) => block.scheduled_date >= todayKey);
  const groupedBlocks = useMemo(() => {
    const groups = new Map<string, StudyBlockWithTask[]>();
    for (const block of visibleBlocks) {
      const list = groups.get(block.scheduled_date) || [];
      list.push(block);
      groups.set(block.scheduled_date, list);
    }
    return [...groups.entries()];
  }, [visibleBlocks]);

  const plannedMinutes = visibleBlocks
    .filter((block) => !block.is_completed)
    .reduce((sum, block) => sum + block.duration_minutes, 0);
  const completedToday = blocks
    .filter((block) => block.scheduled_date === todayKey && block.is_completed)
    .reduce((sum, block) => sum + block.duration_minutes, 0);
  const isLoading = tasksLoading || coursesLoading || blocksLoading || settingsLoading;

  const saveSettingsAndRebuild = async () => {
    try {
      await updateSettings.mutateAsync(draftSettings);
      await buildAndSave(draftSettings, 'settings');
      setSettingsOpen(false);
    } catch (error: any) {
      Alert.alert('Couldn’t save settings', error?.message || 'Please try again.');
    }
  };

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.paper }]} edges={['bottom']}>
      <Stack.Screen options={{ title: 'Smart Plan' }} />
      <ScrollView contentContainerStyle={[styles.content, { maxWidth: contentMaxWidth }]} showsVerticalScrollIndicator={false}>
        <View style={styles.heroRow}>
          <View style={{ flex: 1 }}>
            <Text style={[styles.eyebrow, { color: colors.brand }]}>NEXT {horizonDays} DAYS</Text>
            <Text style={[styles.title, { color: colors.ink }]}>Your study time, already decided.</Text>
            <Text style={[styles.subtitle, { color: colors.ink3 }]}>
              {draftSettings.study_auto_reschedule
                ? 'Missed sessions roll forward each time you open your plan, without colliding with your schedule.'
                : 'Automatic rescheduling is off. Rebuild anytime with the refresh button.'}
            </Text>
          </View>
          <TouchableOpacity
            style={[styles.iconButton, { backgroundColor: colors.card, borderColor: colors.line }]}
            onPress={() => buildAndSave(remoteSettings || draftSettings, 'manual')}
            disabled={replacePlan.isPending || isLoading}
            accessibilityLabel="Rebuild study plan"
          >
            {replacePlan.isPending
              ? <ActivityIndicator size="small" color={colors.brand} />
              : <FontAwesome name="refresh" size={16} color={colors.brand} />}
          </TouchableOpacity>
        </View>

        {/* The upgrade ask sits under a plan the user can already see working,
            rather than replacing it. Free gets a real week; Pro doubles the
            window and turns on the automatic roll-forward. */}
        {!isPro && (
          <TouchableOpacity
            style={[styles.upsell, { backgroundColor: colors.brand50, borderColor: colors.brand100 }]}
            activeOpacity={0.8}
            onPress={() => router.push({ pathname: '/paywall', params: { context: 'smart_planner' } } as any)}
          >
            <FontAwesome name="magic" size={15} color={colors.brand} style={{ marginTop: 1 }} />
            <View style={{ flex: 1 }}>
              <Text style={[styles.upsellTitle, { color: colors.ink }]}>
                You're seeing the next {FREE_STUDY_PLAN_HORIZON_DAYS} days
              </Text>
              <Text style={[styles.upsellText, { color: colors.ink3 }]}>
                Pro plans a full {STUDY_PLAN_HORIZON_DAYS} days ahead and rolls missed sessions
                forward automatically.
              </Text>
            </View>
            <FontAwesome name="chevron-right" size={12} color={colors.brand} style={{ marginTop: 3 }} />
          </TouchableOpacity>
        )}

        {plannerNote && (
          <View style={[styles.statusCard, { backgroundColor: colors.teal50, borderColor: colors.teal }]}>
            <FontAwesome name="check-circle" size={14} color={colors.teal} />
            <Text style={[styles.statusText, { color: colors.teal }]}>{plannerNote}</Text>
          </View>
        )}

        <View style={[styles.summaryCard, { backgroundColor: colors.brand, borderColor: colors.brand }]}> 
          <View>
            <Text style={styles.summaryValue}>{visibleBlocks.filter((block) => !block.is_completed).length}</Text>
            <Text style={styles.summaryLabel}>sessions ahead</Text>
          </View>
          <View style={styles.summaryDivider} />
          <View>
            <Text style={styles.summaryValue}>{formatStudyDuration(plannedMinutes)}</Text>
            <Text style={styles.summaryLabel}>planned</Text>
          </View>
          <View style={styles.summaryDivider} />
          <View>
            <Text style={styles.summaryValue}>{formatStudyDuration(completedToday)}</Text>
            <Text style={styles.summaryLabel}>done today</Text>
          </View>
        </View>

        {lastPlan && lastPlan.atRiskMinutes > 0 && (
          <View style={[styles.warning, { backgroundColor: colors.amber50, borderColor: colors.amber + '40' }]}> 
            <FontAwesome name="exclamation-triangle" size={14} color={colors.amber} />
            <Text style={[styles.warningText, { color: colors.ink2 }]}>Your current capacity leaves {formatStudyDuration(lastPlan.atRiskMinutes)} due within two weeks unscheduled. Increase daily time or reduce task estimates.</Text>
          </View>
        )}

        {!!generationError && (
          <View style={[styles.warning, { backgroundColor: colors.coral50, borderColor: colors.coral + '40' }]}> 
            <Text style={[styles.warningText, { color: colors.coral }]}>{generationError}</Text>
          </View>
        )}

        <TouchableOpacity
          style={[styles.settingsHeader, { backgroundColor: colors.card, borderColor: colors.line }]}
          onPress={() => setSettingsOpen((open) => !open)}
          activeOpacity={0.8}
        >
          <View style={[styles.settingsIcon, { backgroundColor: colors.brand50 }]}>
            <FontAwesome name="sliders" size={14} color={colors.brand} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[styles.settingsTitle, { color: colors.ink }]}>Plan preferences</Text>
            <Text style={[styles.settingsSub, { color: colors.ink3 }]}>{draftSettings.study_daily_minutes}m/day · {draftSettings.study_session_minutes}m sessions</Text>
          </View>
          <FontAwesome name={settingsOpen ? 'chevron-up' : 'chevron-down'} size={11} color={colors.ink3} />
        </TouchableOpacity>

        {settingsOpen && (
          <View style={[styles.settingsCard, { backgroundColor: colors.card, borderColor: colors.line }]}> 
            <Text style={[styles.fieldLabel, { color: colors.ink2 }]}>Daily study capacity</Text>
            <View style={styles.chipRow}>
              {DAILY_MINUTE_OPTIONS.map((minutes) => (
                <TouchableOpacity
                  key={minutes}
                  style={[styles.chip, { borderColor: colors.line }, draftSettings.study_daily_minutes === minutes && { backgroundColor: colors.brand, borderColor: colors.brand }]}
                  onPress={() => setDraftSettings((current) => ({ ...current, study_daily_minutes: minutes }))}
                >
                  <Text style={[styles.chipText, { color: draftSettings.study_daily_minutes === minutes ? '#fff' : colors.ink2 }]}>{formatStudyDuration(minutes)}</Text>
                </TouchableOpacity>
              ))}
            </View>

            <Text style={[styles.fieldLabel, { color: colors.ink2 }]}>Focus session length</Text>
            <View style={styles.chipRow}>
              {STUDY_SESSION_OPTIONS.map((minutes) => (
                <TouchableOpacity
                  key={minutes}
                  style={[styles.chip, { borderColor: colors.line }, draftSettings.study_session_minutes === minutes && { backgroundColor: colors.brand, borderColor: colors.brand }]}
                  onPress={() => setDraftSettings((current) => ({ ...current, study_session_minutes: minutes as StudySessionMinutes }))}
                >
                  <Text style={[styles.chipText, { color: draftSettings.study_session_minutes === minutes ? '#fff' : colors.ink2 }]}>{minutes}m</Text>
                </TouchableOpacity>
              ))}
            </View>

            <View style={styles.timeRow}>
              <View style={{ flex: 1 }}>
                <Text style={[styles.fieldLabel, { color: colors.ink2 }]}>Weekday start</Text>
                <DatePicker
                  value={timeToDate(draftSettings.study_weekday_start)}
                  onChange={(date) => setDraftSettings((current) => ({ ...current, study_weekday_start: dateToTime(date) }))}
                  mode="time"
                />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={[styles.fieldLabel, { color: colors.ink2 }]}>Weekend start</Text>
                <DatePicker
                  value={timeToDate(draftSettings.study_weekend_start)}
                  onChange={(date) => setDraftSettings((current) => ({ ...current, study_weekend_start: dateToTime(date) }))}
                  mode="time"
                />
              </View>
            </View>

            <View style={styles.switchRow}>
              <View style={{ flex: 1 }}>
                <Text style={[styles.settingsTitle, { color: colors.ink }]}>Study on weekends</Text>
                <Text style={[styles.settingsSub, { color: colors.ink3 }]}>Turn off to keep Saturday and Sunday clear.</Text>
              </View>
              <Switch
                value={draftSettings.study_include_weekends}
                onValueChange={(value) => setDraftSettings((current) => ({ ...current, study_include_weekends: value }))}
                trackColor={{ false: colors.line, true: colors.brand100 }}
                thumbColor={draftSettings.study_include_weekends ? colors.brand : '#fff'}
              />
            </View>

            <View style={[styles.switchRow, { borderTopWidth: 0.5, borderTopColor: colors.line }]}>
              <View style={{ flex: 1 }}>
                <Text style={[styles.settingsTitle, { color: colors.ink }]}>Auto-reschedule missed sessions</Text>
                <Text style={[styles.settingsSub, { color: colors.ink3 }]}>Move unfinished study time to the next available slots.</Text>
              </View>
              <Switch
                value={draftSettings.study_auto_reschedule}
                onValueChange={(value) => setDraftSettings((current) => ({ ...current, study_auto_reschedule: value }))}
                trackColor={{ false: colors.line, true: colors.brand100 }}
                thumbColor={draftSettings.study_auto_reschedule ? colors.brand : '#fff'}
              />
            </View>

            <View style={[styles.switchRow, { borderTopWidth: 0.5, borderTopColor: colors.line }]}>
              <View style={{ flex: 1 }}>
                <Text style={[styles.settingsTitle, { color: colors.ink }]}>Avoid calendar conflicts</Text>
                <Text style={[styles.settingsSub, { color: colors.ink3 }]}>Keep sessions clear of classes and events, with a 10-minute buffer.</Text>
              </View>
              <Switch
                value={draftSettings.study_avoid_calendar_conflicts}
                onValueChange={(value) => setDraftSettings((current) => ({ ...current, study_avoid_calendar_conflicts: value }))}
                trackColor={{ false: colors.line, true: colors.brand100 }}
                thumbColor={draftSettings.study_avoid_calendar_conflicts ? colors.brand : '#fff'}
              />
            </View>

            <TouchableOpacity
              style={[styles.saveButton, { backgroundColor: colors.brand }]}
              onPress={saveSettingsAndRebuild}
              disabled={updateSettings.isPending || replacePlan.isPending}
            >
              {(updateSettings.isPending || replacePlan.isPending)
                ? <ActivityIndicator size="small" color="#fff" />
                : <Text style={styles.saveButtonText}>Save & rebuild plan</Text>}
            </TouchableOpacity>
          </View>
        )}

        <View style={styles.sectionHead}>
          <Text style={[styles.sectionTitle, { color: colors.ink }]}>Your sessions</Text>
          <Text style={[styles.sectionMeta, { color: colors.ink3 }]}>Classes are blocked automatically</Text>
        </View>

        {isLoading && visibleBlocks.length === 0 ? (
          <ActivityIndicator style={{ marginTop: 36 }} color={colors.brand} />
        ) : groupedBlocks.length === 0 ? (
          <View style={[styles.emptyCard, { backgroundColor: colors.card, borderColor: colors.line }]}> 
            <View style={[styles.emptyIcon, { backgroundColor: colors.brand50 }]}>
              <FontAwesome name="check" size={18} color={colors.brand} />
            </View>
            <Text style={[styles.emptyTitle, { color: colors.ink }]}>No sessions needed</Text>
            <Text style={[styles.emptyText, { color: colors.ink3 }]}>Add an incomplete task with a due date and Smart Plan will schedule it here.</Text>
          </View>
        ) : (
          groupedBlocks.map(([date, dayBlocks]) => (
            <View key={date} style={styles.daySection}>
              <View style={styles.dayHead}>
                <Text style={[styles.dayTitle, { color: colors.ink2 }]}>{dayLabel(date)}</Text>
                <Text style={[styles.dayTotal, { color: colors.ink3 }]}>{formatStudyDuration(dayBlocks.reduce((sum, block) => sum + block.duration_minutes, 0))}</Text>
              </View>
              <View style={[styles.dayCard, { backgroundColor: colors.card, borderColor: colors.line }]}> 
                {dayBlocks.map((block, index) => (
                  <View key={block.id} style={[styles.blockRow, index < dayBlocks.length - 1 && { borderBottomWidth: 1, borderBottomColor: colors.line }]}> 
                    <TouchableOpacity
                      onPress={() => {
                        toggleBlock.mutate({ id: block.id, is_completed: !block.is_completed });
                        track('study_block_toggled', { completed: !block.is_completed, screen: 'planner' });
                      }}
                      hitSlop={8}
                    >
                      <FontAwesome name={block.is_completed ? 'check-circle' : 'circle-o'} size={20} color={block.is_completed ? colors.teal : colors.ink3} />
                    </TouchableOpacity>
                    <TouchableOpacity style={{ flex: 1 }} onPress={() => router.push(`/task/${block.task_id}` as any)} activeOpacity={0.7}>
                      <View style={styles.blockTitleRow}>
                        <View style={[styles.courseDot, { backgroundColor: block.tasks.courses.color }]} />
                        <Text style={[styles.blockTitle, { color: colors.ink }, block.is_completed && styles.completedText]} numberOfLines={1}>{block.tasks.title}</Text>
                      </View>
                      <Text style={[styles.blockMeta, { color: colors.ink3 }]}>{formatTimeOfDay(block.start_time)} · {block.duration_minutes}m · {block.tasks.courses.name}</Text>
                      {block.reschedule_reason === 'missed' && (
                        <Text style={[styles.movedLabel, { color: colors.teal }]}>Moved from {block.rescheduled_from_date}</Text>
                      )}
                    </TouchableOpacity>
                    {!block.is_completed && (
                      <TouchableOpacity
                        style={[styles.focusButton, { backgroundColor: colors.brand50 }]}
                        onPress={() => router.push({
                          pathname: '/pomodoro',
                          params: {
                            taskId: block.task_id,
                            title: block.tasks.title,
                            minutes: String(block.duration_minutes),
                            blockId: block.id,
                          },
                        } as any)}
                        accessibilityLabel={`Focus on ${block.tasks.title}`}
                      >
                        <FontAwesome name="play" size={10} color={colors.brand} />
                      </TouchableOpacity>
                    )}
                  </View>
                ))}
              </View>
            </View>
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.paper },
  content: { padding: 18, paddingBottom: 80, width: '100%', maxWidth: SCREEN_MAX_WIDTH, alignSelf: 'center' },
  heroRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 16 },
  eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 1, marginBottom: 5 },
  title: { fontFamily: FONTS.displaySemibold, fontSize: 25, lineHeight: 30, letterSpacing: -0.4 },
  subtitle: { fontSize: 13, lineHeight: 19, marginTop: 5 },
  iconButton: { width: 44, height: 44, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  summaryCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', padding: 16, borderRadius: 17, borderWidth: 1, marginBottom: 12 },
  summaryValue: { color: '#fff', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  summaryLabel: { color: '#ffffffbb', fontSize: 10.5, fontWeight: '600', marginTop: 2, textAlign: 'center' },
  summaryDivider: { width: 1, height: 30, backgroundColor: '#ffffff35' },
  warning: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, borderWidth: 1, borderRadius: 12, padding: 11, marginBottom: 12 },
  warningText: { flex: 1, fontSize: 12, lineHeight: 17 },
  statusCard: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 0.5, borderRadius: 12, padding: 10, marginBottom: 12 },
  statusText: { flex: 1, fontSize: 11.5, lineHeight: 16, fontWeight: '600' },
  settingsHeader: { minHeight: 64, borderWidth: 1, borderRadius: 15, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 10 },
  settingsIcon: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  settingsTitle: { fontSize: 14, fontWeight: '700' },
  settingsSub: { fontSize: 11.5, marginTop: 2, lineHeight: 16 },
  settingsCard: { borderWidth: 1, borderRadius: 15, padding: 14, marginBottom: 18 },
  fieldLabel: { fontSize: 12, fontWeight: '700', marginTop: 10, marginBottom: 8 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { minWidth: 58, height: 38, borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 11 },
  chipText: { fontSize: 12, fontWeight: '700' },
  timeRow: { flexDirection: 'row', gap: 10 },
  switchRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 17 },
  saveButton: { height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 18 },
  saveButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  sectionHead: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 12, marginBottom: 10 },
  sectionTitle: { fontFamily: FONTS.displaySemibold, fontSize: 18 },
  sectionMeta: { fontSize: 10.5, fontWeight: '600' },
  daySection: { marginBottom: 16 },
  dayHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 7 },
  dayTitle: { fontSize: 13, fontWeight: '700' },
  dayTotal: { fontSize: 11.5, fontWeight: '600' },
  dayCard: { borderWidth: 1, borderRadius: 15, overflow: 'hidden' },
  blockRow: { minHeight: 72, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 11 },
  blockTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  courseDot: { width: 7, height: 7, borderRadius: 4 },
  blockTitle: { flex: 1, fontSize: 14, fontWeight: '700' },
  blockMeta: { fontSize: 11.5, marginTop: 4 },
  movedLabel: { fontSize: 10.5, fontWeight: '700', marginTop: 2 },
  completedText: { textDecorationLine: 'line-through', opacity: 0.55 },
  focusButton: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  emptyCard: { alignItems: 'center', borderWidth: 1, borderRadius: 16, padding: 26 },
  emptyIcon: { width: 46, height: 46, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  emptyTitle: { fontSize: 16, fontWeight: '700', marginTop: 12 },
  emptyText: { fontSize: 12.5, lineHeight: 18, textAlign: 'center', marginTop: 5 },
  // Free-tier upgrade banner. Replaced the old full-screen lock styles when
  // Smart Plan stopped being all-or-nothing for free users.
  upsell: { flexDirection: 'row', alignItems: 'flex-start', gap: 11, borderWidth: 1, borderRadius: 14, padding: 14, marginBottom: 18 },
  upsellTitle: { fontSize: 14, fontWeight: '700' },
  upsellText: { fontSize: 13, lineHeight: 19, marginTop: 3 },
});
