#!/usr/bin/env bash
# Build + run Semora on the Android emulator.
#
# Android is NOT installed system-wide on this Mac — the SDK lives under
# Homebrew and nothing is exported in ~/.zshrc, so these three vars have to be
# set for every gradle/adb/emulator call. The android/ directory is gitignored
# and regenerated by `expo prebuild -p android`.
set -euo pipefail

export JAVA_HOME=/opt/homebrew/opt/openjdk@17
export ANDROID_HOME=/opt/homebrew/share/android-commandlinetools
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"

AVD=Semora_Pixel7
PKG=com.rajeshpanta.syllabussnap
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

[ -d "$ROOT/android" ] || npx expo prebuild -p android --no-install

if ! adb devices | grep -q "emulator-.*device"; then
  echo "› booting $AVD"
  "$ANDROID_HOME/emulator/emulator" -avd "$AVD" -no-snapshot-save -no-boot-anim >/dev/null 2>&1 &
  adb wait-for-device
  until [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" = "1" ]; do sleep 3; done
fi

(cd "$ROOT/android" && ./gradlew :app:assembleDebug --console=plain)
adb install -r "$ROOT/android/app/build/outputs/apk/debug/app-debug.apk"

# Metro must be reachable from inside the emulator.
adb reverse tcp:8081 tcp:8081
curl -sf http://localhost:8081/status >/dev/null || echo "! Metro is not running — start it with: npx expo start"

adb shell monkey -p "$PKG" -c android.intent.category.LAUNCHER 1 >/dev/null
echo "› launched $PKG"
