-- ============================================================
-- REFERRALS — free Pro month for BOTH sides (growth engine)
-- ============================================================
-- Each user has ONE unguessable referral code (created lazily). When a
-- new user redeems someone's code, BOTH the referrer and the referred
-- user get a 30-day promo grant of Pro.
--
-- CRITICAL ENTITLEMENT DESIGN (see migration 009):
--   public.entitlements is written by the validate-receipt edge function
--   on EVERY purchase validation. Any Pro row we wrote there for a promo
--   would be CLOBBERED the next time validate-receipt ran (it upserts the
--   whole row from Apple's answer). So promo Pro is NOT stored in
--   entitlements. Instead it lives in its own promo_grants table, and
--   is_pro() is redefined below to OR-in an active promo grant. This way a
--   real subscription (entitlements) and a promo grant simply BOTH count,
--   and validate-receipt can never wipe a promo.
--
-- Three tables:
--   referral_codes       — one code per user (pk = user_id)
--   referral_redemptions — who redeemed whose code (a user can be
--                          REFERRED only once — unique on referred_user_id)
--   promo_grants         — service-role-written Pro grants with an expiry;
--                          owner-readable so the client can reflect promo Pro
--
-- Cross-tenant safety: referrer_user_id / referred_user_id are auth.users
-- FKs (both apps share auth.users but these are Semora-owned tables). The
-- redeem-referral edge function (service role) is the ONLY writer of
-- redemptions + grants, so no client can fabricate a grant.
--
-- SEMORA-owned (verify against supabase/SUPABASE_OWNERSHIP.md). Additive
-- only. Tagged via COMMENT ON TABLE per the ownership convention so the
-- shared-project audit (Semora + Citizen) can attribute it correctly.
-- ============================================================

-- ─── referral_codes ─────────────────────────────────────────────
-- One row per user. `code` is unguessable (generated by the edge
-- function / getMyCode, not derivable from the user_id) and unique so it
-- can be handed out in a share link (semora://invite?code=...).
create table if not exists public.referral_codes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now(),
  constraint referral_codes_code_not_blank check (length(btrim(code)) > 0)
);
create index if not exists referral_codes_code_idx on public.referral_codes(code);

-- ─── referral_redemptions ───────────────────────────────────────
-- One row per successful redemption. referred_user_id is UNIQUE: a user
-- can be REFERRED only once (they can't stack free months by redeeming
-- multiple codes). referrer_user_id is NOT unique — a referrer can refer
-- many friends (subject to the server-side active-grant cap).
create table if not exists public.referral_redemptions (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  -- A user can never redeem their own code — enforced server-side too, but
  -- a table constraint makes it impossible even via a service-role bug.
  constraint referral_redemptions_no_self check (referrer_user_id <> referred_user_id)
);
create index if not exists referral_redemptions_referrer_idx
  on public.referral_redemptions(referrer_user_id);

-- ─── promo_grants ───────────────────────────────────────────────
-- A time-boxed Pro grant NOT tied to a purchase. Written ONLY by the
-- service_role (redeem-referral edge function). is_pro() counts a grant
-- as active while expires_at > now(). `reason` records why it was granted
-- ('referral_referrer' | 'referral_referred', extensible later).
create table if not exists public.promo_grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  granted_at timestamptz not null default now(),
  expires_at timestamptz not null
);
-- is_pro() filters promo_grants by user_id + expires_at > now(); a
-- composite index keeps that check cheap as grants accumulate.
create index if not exists promo_grants_user_expires_idx
  on public.promo_grants(user_id, expires_at);

-- Tag ownership in the DB so the shared-project audit can attribute these
-- tables without cross-referencing the repo.
comment on table public.referral_codes is
  'SEMORA: one unguessable referral code per user (created lazily).';
comment on table public.referral_redemptions is
  'SEMORA: referral redemptions (referred_user_id unique — a user is referred at most once).';
comment on table public.promo_grants is
  'SEMORA: time-boxed Pro grants not tied to a purchase (referrals). Service-role write only; counted by is_pro().';

-- ─── RLS ────────────────────────────────────────────────────────
-- referral_codes: a user reads (and lazily creates) ONLY their own code.
-- getMyCode() inserts the row client-side, so an INSERT policy is needed;
-- the code value itself is generated client-side as an unguessable string.
alter table public.referral_codes enable row level security;

create policy "read_own_referral_code" on public.referral_codes
  for select to authenticated
  using (auth.uid() = user_id);

create policy "insert_own_referral_code" on public.referral_codes
  for insert to authenticated
  with check (auth.uid() = user_id);
-- No UPDATE/DELETE policy — a code is immutable once created.

-- referral_redemptions: owner-readable so a referrer can see "N friends
-- joined" (they read rows where they are the referrer) and a referred user
-- can see their own redemption. NO client INSERT policy — only the
-- service_role (redeem-referral) writes here, so the guards (self-referral,
-- already-referred, code-exists, referrer cap) can't be bypassed by a
-- direct REST insert.
alter table public.referral_redemptions enable row level security;

create policy "read_own_referral_redemptions" on public.referral_redemptions
  for select to authenticated
  using (auth.uid() = referrer_user_id or auth.uid() = referred_user_id);

-- promo_grants: owner-readable so the client can reflect promo Pro in the
-- UI (isPro derives from entitlements only, which never carries a promo —
-- see lib/referral.hasActivePromoGrant). NO client write policy; the
-- service_role bypasses RLS and is the only writer.
alter table public.promo_grants enable row level security;

create policy "read_own_promo_grants" on public.promo_grants
  for select to authenticated
  using (auth.uid() = user_id);

-- ============================================================
-- is_pro(uuid) — REDEFINED to OR-in an active promo grant
-- ============================================================
-- This is the SENSITIVE change. is_pro() gates every Pro feature (RLS,
-- the free course/scan/semester triggers, and the parse-syllabus /
-- tutor-chat edge functions). The body below preserves the EXACT logic
-- from migration 009 (an active, unexpired entitlement row) and only ADDS
-- a second branch: an active, unexpired promo_grant. Either one makes the
-- user Pro. Kept SECURITY DEFINER / stable / search_path=public with the
-- same grants as 009 — nothing else about the function changes.
--
-- A promo grant thus grants Pro WITHOUT touching entitlements, so
-- validate-receipt never clobbers it, and a real subscription + a promo
-- simply both count.
-- ============================================================
create or replace function public.is_pro(uid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select
    -- Branch 1: a valid, unexpired purchased entitlement (verbatim from 009).
    coalesce(
      (
        select e.is_pro
          and (e.expires_at is null or e.expires_at > now())
        from public.entitlements e
        where e.user_id = uid
        limit 1
      ),
      false
    )
    -- Branch 2: an active (unexpired) promo grant — referral free month, etc.
    or exists (
      select 1
      from public.promo_grants g
      where g.user_id = uid
        and g.expires_at > now()
    );
$$;

-- Preserve migration 009's grants exactly — the redefinition above reset the
-- function body but not its ACL; re-assert to be explicit and idempotent.
revoke all on function public.is_pro(uuid) from public, anon, authenticated;
grant execute on function public.is_pro(uuid) to service_role;

-- ============================================================
-- try_redeem_referral(code, referred) — atomic redemption
-- ============================================================
-- Called by the redeem-referral edge function (service role). Serializes
-- per-referred-user via a transaction advisory lock and enforces ALL guards
-- as one atomic step so a concurrent double-tap can't create two redemptions
-- or two pairs of grants:
--   * the code must exist (→ 'invalid_code')
--   * the referred user can't redeem their OWN code (→ 'self_referral')
--   * the referred user can't already be referred (→ 'already_redeemed')
--   * the referrer's active promo grants are capped (→ 'referrer_capped')
-- On success: inserts the redemption + a 30-day promo grant for BOTH users,
-- and returns 'ok'. SECURITY DEFINER + service_role-only so clients can't
-- call it to fabricate grants.
--
-- max_active_grants caps how many active (unexpired) referral grants a
-- single referrer can hold — a coarse anti-fraud ceiling (OAuth-only signup
-- already limits sock-puppets). Passed in so the edge function owns the number.
create or replace function public.try_redeem_referral(
  redeem_code text,
  referred uuid,
  max_active_grants int
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  referrer uuid;
  active_referrer_grants int;
  grant_days constant int := 30;
begin
  -- Serialize concurrent redemptions for THIS referred user so the
  -- already-referred check and the insert are one atomic step.
  perform pg_advisory_xact_lock(hashtext('referral_redeem:' || referred::text));

  -- Resolve the code to a referrer.
  select rc.user_id into referrer
    from public.referral_codes rc
    where rc.code = redeem_code
    limit 1;
  if referrer is null then
    return 'invalid_code';
  end if;

  -- Can't redeem your own code.
  if referrer = referred then
    return 'self_referral';
  end if;

  -- A user can be referred only once (unique on referred_user_id backs this
  -- up, but check explicitly for a clean status instead of a 23505).
  if exists (
    select 1 from public.referral_redemptions r
    where r.referred_user_id = referred
  ) then
    return 'already_redeemed';
  end if;

  -- Cap the referrer's active (unexpired) referral grants — anti-fraud.
  select count(*) into active_referrer_grants
    from public.promo_grants g
    where g.user_id = referrer
      and g.reason = 'referral_referrer'
      and g.expires_at > now();
  if active_referrer_grants >= max_active_grants then
    return 'referrer_capped';
  end if;

  -- All guards passed — record the redemption and grant BOTH sides a month.
  insert into public.referral_redemptions (code, referrer_user_id, referred_user_id)
    values (redeem_code, referrer, referred);

  insert into public.promo_grants (user_id, reason, expires_at) values
    (referrer, 'referral_referrer', now() + (grant_days || ' days')::interval),
    (referred, 'referral_referred', now() + (grant_days || ' days')::interval);

  return 'ok';
end;
$$;

revoke all on function public.try_redeem_referral(text, uuid, int) from public, anon, authenticated;
grant execute on function public.try_redeem_referral(text, uuid, int) to service_role;
